name: cinema_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.6
  flutter_screenutil: ^5.9.1
  http: ^1.2.1
  font_awesome_flutter: ^10.4.0
  flutter_staggered_animations: ^1.1.1
  motion_tab_bar: ^2.0.4
  searchfield: ^1.0.3
  avatar_glow: ^3.0.1
  firebase_database: ^10.5.6
  cloud_firestore: ^4.17.5
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
